# Use the official Python image as the base image
FROM python:3

# Set the working directory inside the container
WORKDIR /app

# Copy the game code into the container
COPY rock_paper_scissors2.py /app/

# Run the game when the container starts
CMD ["python3", "rock_paper_scissors2.py"]
